In [2]:
!pip install numpy --upgrade


Requirement already up-to-date: numpy in c:\users\user\anaconda3\lib\site-packages (1.18.2)


In [5]:
import numpy as np
array_one=np.array([1,2,3,4])


In [6]:
array_one

array([1, 2, 3, 4])

In [7]:
type(array_one)

numpy.ndarray

In [8]:
numbers=[5,6,7,8,9]

In [9]:
array_two=np.array(numbers)

In [10]:
array_two

array([5, 6, 7, 8, 9])

In [11]:
array_of_zeros=np.zeros([3,4])

In [12]:
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
array_sd=np.array([5,6])

In [14]:
array_sd

array([5, 6])

In [15]:
array_of_ones=np.ones([3,3])

In [16]:
array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])