In [9]:
import numpy as np


In [20]:
A=np.array([[1,2],[2,3]])
B=np.array([[4,5],[3,6]])
print('A:\n',A)
print('B:\n',B)

A:
 [[1 2]
 [2 3]]
B:
 [[4 5]
 [3 6]]


In [21]:
A*B

array([[ 4, 10],
       [ 6, 18]])

In [22]:
A.dot(B)

array([[10, 17],
       [17, 28]])

In [23]:
a=np.array([5,6,7])

In [25]:
b=np.array([9,7,6])

In [26]:
a+b


array([14, 13, 13])

In [27]:
a-b

array([-4, -1,  1])

In [28]:
a*b

array([45, 42, 42])

In [29]:
a%b

array([5, 6, 1], dtype=int32)

In [30]:
num=np.array([12,5,6,7])

In [31]:
num.sum()

30

In [32]:
num.min()

5

In [33]:
num.max()

12

In [36]:
num.size

4

In [37]:
num[:]

array([12,  5,  6,  7])

In [38]:
num[-1]

7

In [39]:
num[1]=9

In [40]:
num

array([12,  9,  6,  7])

In [48]:
stu=np.arange(15).reshape(3,5)
stu


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
stu.sum(axis=0)

array([15, 18, 21, 24, 27])

In [57]:
stu.sum(axis=1)

array([10, 35, 60])

In [66]:
test=np.array([12.3,34,22.34,56,11,10,3.34,5])

In [69]:
print('mean test score of the students:')
print(np.mean(test))


mean test score of the students:
19.2475


In [68]:
print(np.mean(test))

19.2475


In [71]:
print(np.median(test))

11.65
