In [1]:
import numpy as np

In [3]:
salaries=np.genfromtxt('salary.csv',delimiter=',')

In [4]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [5]:
salaries.shape

(1147,)

In [7]:
mean=np.mean(salaries)

median=np.median(salaries)

In [8]:
median=np.median(salaries)


In [9]:
sd=np.std(salaries)

In [10]:
variance=np.var(salaries)

In [12]:
print('Mean=%i'%mean)

Mean=55894


In [13]:
print('Median=%i'%median)

Median=48000


In [14]:
print('Standard Deviation=%i'%sd)

Standard Deviation=55170


In [17]:
print('Variance=%i'%variance)

Variance=3043770333


In [19]:
friends=np.array([['naveen','sai','venkat','balaji','vamsi','sanjaya'],
                 
                 
                [45,55,65,75],[67,87,97,47]])

In [20]:
print(friends)

[list(['naveen', 'sai', 'venkat', 'balaji', 'vamsi', 'sanjaya'])
 list([45, 55, 65, 75]) list([67, 87, 97, 47])]


In [21]:
friends[0]

['naveen', 'sai', 'venkat', 'balaji', 'vamsi', 'sanjaya']

In [23]:
friends[0:2]

array([list(['naveen', 'sai', 'venkat', 'balaji', 'vamsi', 'sanjaya']),
       list([45, 55, 65, 75])], dtype=object)

In [24]:
friends[0:1]

array([list(['naveen', 'sai', 'venkat', 'balaji', 'vamsi', 'sanjaya'])],
      dtype=object)

In [29]:
friends[2:1]

array([], dtype=object)

In [37]:
stu=np.array([['ram','fyz','kaka'],[23,45,67]])

In [38]:
students=np.array([['ram','vinay','vikram','vanu'],
                  [45,55,65,75],[67,76,89,90]])

In [39]:
students

array([['ram', 'vinay', 'vikram', 'vanu'],
       ['45', '55', '65', '75'],
       ['67', '76', '89', '90']], dtype='<U6')

In [40]:
a=np.arange(11)**2

In [41]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [42]:
for i in a:
    print(i)

0
1
4
9
16
25
36
49
64
81
100


In [43]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [76]:
for events in students:
    print('j=',events)

j= ['ram' 'vinay' 'vikram' 'vanu']
j= ['45' '55' '65' '75']
j= ['67' '76' '89' '90']


In [47]:
for events in students.flatten():
    print(events)

ram
vinay
vikram
vanu
45
55
65
75
67
76
89
90


In [58]:
students=np.array([['ram','vinay','vikram','vanu'],
                  [45,55,65,75],[67,76,89,90]])

In [66]:
for i in students(order='F'):
    print(i)

TypeError: 'numpy.ndarray' object is not callable

In [60]:
x=np.arange(12).reshape(3,4)

In [61]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [77]:
for i in np.nditer(x,order='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [78]:
students=np.array([['ram','vinay','vikram','vanu'],
                  [45,55,65,75],[67,76,89,90]])

In [79]:
students

array([['ram', 'vinay', 'vikram', 'vanu'],
       ['45', '55', '65', '75'],
       ['67', '76', '89', '90']], dtype='<U6')

In [83]:
for y in students.flatten(order='F'):
    print(y)

ram
45
67
vinay
55
76
vikram
65
89
vanu
75
90
